# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: 'pip install cram'
  - init: 'rustup target add wasm32-unknown-unknown'
  - init: 'cargo install trunk'
  - init: 'cargo install hyper_cgi --features=test-server'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 8000
#     onOpen: open-preview
