[package]
name = "josh-git-serde"
version = "26.8.28"
repository = "https://github.com/josh-project/josh"
license-file = "../LICENSE"
description = "serde serialization of Rust values into git tree objects"
keywords = ["git", "serde", "tree"]
readme = "../README.md"
edition = "2024"

[dependencies]
anyhow.workspace = true
gix-object.workspace = true
gix-hash.workspace = true
percent-encoding = "2.3.2"
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
josh-gix-ext.workspace = true
