[package]
authors = ["Josh Project authors <contact@josh-project.dev>"]
description = "Josh container workspace runner"
edition = "2024"
keywords = ["git", "monorepo", "workflow", "scm"]
license-file = "../LICENSE"
name = "josh-compose"
readme = "../README.md"
repository = "https://github.com/josh-project/josh"
version = "26.8.28"

[dependencies]
anyhow.workspace = true
defer.workspace = true
gix-hash.workspace = true
josh-core.workspace = true
josh-filter.workspace = true
josh-compose-backend.workspace = true

tar = "0.4"

[dev-dependencies]
gix.workspace = true
tempfile.workspace = true
