# syntax=docker/dockerfile:1.23.0@sha256:2780b5c3bab67f1f76c781860de469442999ed1a0d7992a5efdf2cffc0e3d769

ARG ALPINE_VERSION=3.22.0

FROM alpine:${ALPINE_VERSION}

RUN apk add --no-cache bash ca-certificates git go
