[package]
name = "josh-ssh-shell"
version = "0.1.0"

[dependencies]
clap = { version = "4.0.9", features = ["derive", "help", "std", "usage"], default-features = false }
libc = "0.2.134"
shell-words = "1.1.0"
