WHITESPACE = _{ " " | "\t" }
CMD_START = _{(":"|"!")}
CMD_END = _{("="|"/")}


filter_spec = { (filter | filter_noarg)* }

filter = { CMD_START ~ cmd ~ CMD_END ~ argument }

filter_noarg = { CMD_START ~ cmd }

argument = { (!(CMD_START | NEWLINE) ~ ANY)+ }

cmd = { (!(CMD_END | NEWLINE | CMD_START) ~ ANY)* }

workspace_file = { NEWLINE* ~ file_entry ~ (NEWLINE+ ~ file_entry)* }

file_entry = { dst_path ~ "=" ~ filter_spec }

dst_path = @{ (!("=" | WHITESPACE) ~ ANY)+ }
