name: github-pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MDBOOK_MERMAID_VERSION: '0.17.0'

    steps:
      - uses: actions/checkout@v6

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.5.2'

      - name: Install mdbook-mermaid
        run: |
          curl -L -o mdbook-mermaid.tar.gz \
            https://github.com/badboy/mdbook-mermaid/releases/download/v${{ env.MDBOOK_MERMAID_VERSION }}/mdbook-mermaid-v${{ env.MDBOOK_MERMAID_VERSION }}-x86_64-unknown-linux-musl.tar.gz
          tar -xzf mdbook-mermaid.tar.gz
          chmod +x mdbook-mermaid
          sudo mv mdbook-mermaid /usr/local/bin/
          mdbook-mermaid install docs/

      - run: mdbook build docs/

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
