name: docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/build-docs.sh'
      - '.github/workflows/pages.yml'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/build-docs.sh'
      - '.github/workflows/pages.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      MDBOOK_MERMAID_VERSION: '0.17.0'
      MDBOOK_MERMAID_SHA256: 'c3a924da1c1895d694f0544fb8ce71ae01508138d8e9b02374e9bf608ae765d7'
      MDBOOK_I18N_HELPERS_VERSION: '0.4.0'
      MDBOOK_I18N_HELPERS_SHA256: '262aa71164ff22267eca2f252fcab092001b43685d107135263fc5922f1086fe'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 # v2.0.0
        with:
          mdbook-version: '0.5.2'

      - name: Install mdbook-mermaid
        working-directory: ${{ runner.temp }}
        run: |
          curl -L -o mdbook-mermaid.tar.gz \
            https://github.com/badboy/mdbook-mermaid/releases/download/v${{ env.MDBOOK_MERMAID_VERSION }}/mdbook-mermaid-v${{ env.MDBOOK_MERMAID_VERSION }}-x86_64-unknown-linux-musl.tar.gz
          echo "${{ env.MDBOOK_MERMAID_SHA256 }}  mdbook-mermaid.tar.gz" | sha256sum -c -
          tar -xzf mdbook-mermaid.tar.gz
          chmod +x mdbook-mermaid
          sudo mv mdbook-mermaid /usr/local/bin/

      - name: Install mdbook i18n helpers
        working-directory: ${{ runner.temp }}
        run: |
          curl -L -o mdbook-i18n-helpers.tar.gz \
            https://github.com/cargo-bins/cargo-quickinstall/releases/download/mdbook-i18n-helpers-${{ env.MDBOOK_I18N_HELPERS_VERSION }}/mdbook-i18n-helpers-${{ env.MDBOOK_I18N_HELPERS_VERSION }}-x86_64-unknown-linux-musl.tar.gz
          echo "${{ env.MDBOOK_I18N_HELPERS_SHA256 }}  mdbook-i18n-helpers.tar.gz" | sha256sum -c -
          tar -xzf mdbook-i18n-helpers.tar.gz
          chmod +x mdbook-gettext mdbook-i18n-normalize mdbook-xgettext
          sudo mv mdbook-gettext mdbook-i18n-normalize mdbook-xgettext /usr/local/bin/

      - name: Build docs
        run: |
          .github/workflows/build-docs.sh en_001 docs
          .github/workflows/build-docs.sh zh_CN  docs/zh_CN
